
#POST http://localhost:3000/items
POST https://asia-northeast1-flea-market-fb770.cloudfunctions.net/api/items
#POST http://localhost:5001/flea-market-fb770/asia-northeast1/api/items
Content-Type: application/json

{
  "name": "TV",
  "price": 50000,
  "description": "汚いです"
}

###
#GET http://localhost:3000/items
GET https://asia-northeast1-flea-market-fb770.cloudfunctions.net/api/items
Accept: application/json

###

GET http://localhost:3000/items/001a546e-8288-411d-bc94-9b0bd835584b
Accept: application/json

###

PATCH http://localhost:3000/items/test2
Accept: application/json

###

DELETE http://localhost:3000/items/test2
Accept: application/json

###

