
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "PC",
  "price": 50000,
  "description": "とても綺麗です"
}

###
GET http://localhost:3000/items
Accept: application/json

###

GET http://localhost:3000/items/001a546e-8288-411d-bc94-9b0bd835584b
Accept: application/json

###

PATCH http://localhost:3000/items/test2
Accept: application/json

###

DELETE http://localhost:3000/items/test2
Accept: application/json

###

